### PR TITLE
Change trueDistanceTo to use the Math.hypot function, which avoids ge…

### PR DESCRIPTION
**Pull request by perkinslr**
Change trueDistanceTo to use the Math.hypot function, which avoids getting NAN from Math.sqrt on large intermediate values

### CODE REVIEW

**Comment by perkinslr** [comment]
trueDistanceTo is used by the transporter for calculating the power cost.  About a few km away, Math.sqrt chokes on1000**2, and the transporter fails to calculate the power requirements.

**Comment by Baughn** [comment]
Please send your PRs to https://github.com/Dolu1990/. This branch exists purely as backup/synchronization for my various machines.

**Comment by Baughn** [comment]
That said, Math.sqrt should definitely not be choking on that; a few million is still a small number. Are you sure that's what's happening?

**Comment by perkinslr** [comment]
Okay, fair enough, there just hasn't been any activity on that fork for a couple months, and I pulled my version from your 'release' branch, so I thought I'd offer it here.  You're right, 1000**2 is fine, sqrt(46341 \* 46341) is the lowest value on my laptop that returns NaN.  The players that noticed it were about 35km apart (opposite directions from the global spawn).

**Comment by Baughn** [comment]
Ah, got it. Yes, I can see how that might happen now.

Another solution, actually, would be to use doubles instead of ints... but I like your better; let's use library code whenever possible. That said, this would still be the wrong branch even if I were the main maintainer, which I'm not. :)

**Comment by perkinslr** [comment]
Aye, and using doubles would give a more precise answer, but it's also much slower than hypot's approximate method, and hypot's method is accurate up to the last included digit.  Using doubles would let you use a single Math.\* call, vs hypot which only works with 2 values, so I'm not sure which would be faster overall.  Like you say, I like the library code.

**Pull request closed without merging**
